on:
  push:
    branches:
      - master

jobs:
#  release-android:
#    name: Build and distribute Android app
#    #if: github.event.pull_request.merged == true
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: '3.0'
#
#      - uses: subosito/flutter-action@v1
#        with:
#          flutter-version: '3.3.3'
#
#      - name: Update Flutter dependencies
#        run: flutter clean && flutter pub get
#
#      - name: Install Fastlane
#        run: cd android && bundle update --bundler && cd ..
#
#      - name: Execute Fastlane command
#        run: cd android && fastlane android staging

  release-ios:
    name: Build and distribute IOS app to TestFlight

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.3'

      - name: "Check WATCHKEY_APP_SECRET"
        env:
          WATCHKEY_APP_SECRET: ${{secrets.WATCHKEY_APP_SECRET}}
        if: env.WATCHKEY_APP_SECRET == 'Trust'
          run: echo ${{env.WATCHKEY_APP_SECRET}}
#
#      - name: Update Flutter dependencies
#        run: flutter clean && flutter pub get
#
#      - name: Install Fastlane
#        run: cd ios && gem install cocoapods && pod install && cd ..
#
#      - name: Execute Fastlane command
#        run: cd ios && fastlane ios staging
